timeout: '1200s'  # 10min

steps:
  # maven:3-eclipse-temurin-21. Pin sha for reproducible builds
  - name: maven@sha256:e895a7e85a1acb128d3670fa3ee45f2a9f07836b28364d19a4ab2916f9dd2e14
    entrypoint: bash
    args:
      - -c
      - |
        ls -al
dependencies:
  - gitSource:
      repository:
        developerConnect: "projects/louhi-test/locations/us-central1/connections/louhi-github-developer-connect-porcupine/gitRepositoryLinks/porc-jul10-frontend"
      revision: "${_REF_SHA}"
      destPath: "."
