name: hello-world-presubmit
on:
  pull_request:
    branches: [ 'master' ]
jobs:
  my-job-presubmit:
    runs-on:
      group: default
      labels: arc-runners
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
